//! Build-time utilities for [eq_ui](https://crates.io/crates/eq_ui).
//!
//! This crate is intended for use as a **build dependency** (`[build-dependencies]`).
//! It has zero dependencies and provides a single function that scans a folder of
//! SVG files and generates a Rust source file with `pub const` path data entries,
//! ready for use with `EqIcon { path: ... }`.
//!
//! # Setup
//!
//! Add both crates to your `Cargo.toml`:
//!
//! ```toml
//! [dependencies]
//! eq_ui = "0.1"
//!
//! [build-dependencies]
//! eq_ui_build = "0.1"
//! ```
//!
//! # Usage
//!
//! Create a `build.rs` at your crate root (next to `Cargo.toml`):
//!
//! ```ignore
//! fn main() {
//!     eq_ui_build::generate_icon_paths(
//!         "assets/icons",         // folder containing your .svg files
//!         "my_icon_paths.rs",     // output file name (written to OUT_DIR)
//!     );
//! }
//! ```
//!
//! Then include the generated file in your source code:
//!
//! ```ignore
//! // src/icons.rs (or any file you choose)
//! include!(concat!(env!("OUT_DIR"), "/my_icon_paths.rs"));
//! ```
//!
//! # How it works
//!
//! The function reads every `.svg` file in the given folder, extracts the `d`
//! attribute from the first `<path>` element, and writes a `pub const` entry
//! for each one. The constant name is derived from the file name:
//!
//! | SVG file | Constant |
//! |---|---|
//! | `arrow-right.svg` | `ARROW_RIGHT` |
//! | `caret-up-down.svg` | `CARET_UP_DOWN` |
//! | `star.svg` | `STAR` |
//! | `my_custom_icon.svg` | `MY_CUSTOM_ICON` |
//!
//! The naming rule: hyphens and underscores in the file name become underscores,
//! and the result is uppercased. You can use any file name you like.
//!
//! # Notes
//!
//! - Only `.svg` files are processed; other files in the folder are ignored.
//! - The SVG must contain at least one `<path d="...">` element.
//! - If the folder does not exist, an empty file is generated (no error).
//! - The build script reruns automatically when the folder contents change.

use std::env;
use std::fs;
use std::path::Path;

/// Scan a folder of SVG files and generate a Rust source file with
/// `pub const` path data entries.
///
/// # Arguments
///
/// * `svg_folder` - path to the folder containing `.svg` files,
///   relative to the crate root.
/// * `output_file` - name of the generated `.rs` file. Written inside
///   Cargo's `OUT_DIR`. Include it in your code with:
///   `include!(concat!(env!("OUT_DIR"), "/your_file.rs"));`
///
/// # Panics
///
/// Panics if a `.svg` file is found but does not contain a valid
/// `<path d="...">` attribute.
pub fn generate_icon_paths(svg_folder: &str, output_file: &str) {
    let icons_dir = Path::new(svg_folder);
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set - this function must be called from build.rs");
    let dest = Path::new(&out_dir).join(output_file);

    // Tell Cargo to rerun when the icon folder changes.
    println!("cargo:rerun-if-changed={}", svg_folder);

    let mut output = String::from(
        "// Auto-generated by eq_ui_build - do not edit manually.\n\n",
    );

    if !icons_dir.exists() {
        fs::write(&dest, &output).expect("failed to write generated icon file");
        return;
    }

    let mut entries: Vec<_> = fs::read_dir(icons_dir)
        .unwrap_or_else(|_| panic!("failed to read folder: {}", svg_folder))
        .filter_map(|e| e.ok())
        .filter(|e| {
            e.path()
                .extension()
                .map(|ext| ext == "svg")
                .unwrap_or(false)
        })
        .collect();

    // Sort for deterministic output.
    entries.sort_by_key(|e| e.file_name());

    for entry in entries {
        let path = entry.path();
        let stem = path
            .file_stem()
            .expect("no file stem")
            .to_string_lossy()
            .to_string();

        let svg = fs::read_to_string(&path)
            .unwrap_or_else(|_| panic!("failed to read {}", path.display()));

        let d = extract_path_d(&svg)
            .unwrap_or_else(|| panic!(
                "could not extract path `d` attribute from {}",
                path.display()
            ));

        let const_name = stem.replace('-', "_").to_uppercase();
        output.push_str(&format!(
            "pub const {}: &str =\n    \"{}\";\n\n",
            const_name,
            d.replace('\\', "\\\\").replace('"', "\\\""),
        ));
    }

    fs::write(&dest, &output).expect("failed to write generated icon file");
}

/// Extract the `d` attribute value from the first `<path d="...">` in an SVG string.
fn extract_path_d(svg: &str) -> Option<String> {
    let path_start = svg.find("<path")?;
    let after_path = &svg[path_start..];

    let d_start = after_path.find("d=\"")?;
    let d_value = &after_path[d_start + 3..];

    let d_end = d_value.find('"')?;
    Some(d_value[..d_end].to_string())
}
