//! SVG path data for use with `EqIcon { path: ... }`.
//!
//! ## Bundled icons
//!
//! Auto-generated at compile time by `build.rs` from the SVG files in
//! `assets/icons/`. Each constant contains the `d` attribute value from
//! the corresponding SVG `<path>` element.
//!
//! To add a new icon to the library:
//! 1. Copy the SVG file into `assets/icons/`
//! 2. Register it in `assets/icons/ICON_REGISTRY.md`
//! 3. Rebuild — the constant appears automatically
//!    (e.g. `my-icon.svg` → `MY_ICON`)
//!
//! Source: Phosphor Icons (regular weight, MIT licensed).
//! See `assets/icons/ICON_REGISTRY.md` for full attribution.
//!
//! ## Custom icons
//!
//! Consumers can generate their own icon constants from a folder of SVG
//! files using the [`eq_ui_build`](https://crates.io/crates/eq_ui_build)
//! crate. Add it as a build dependency:
//!
//! ```toml
//! [dependencies]
//! eq_ui = "0.1"
//!
//! [build-dependencies]
//! eq_ui_build = "0.1"
//! ```
//!
//! Create a `build.rs` at your project root:
//!
//! ```ignore
//! fn main() {
//!     eq_ui_build::generate_icon_paths(
//!         "assets/icons",        // your SVG folder (any name)
//!         "my_icon_paths.rs",    // output file name (any name)
//!     );
//! }
//! ```
//!
//! Include the generated file wherever you like:
//!
//! ```ignore
//! // src/icons.rs (or any file you choose)
//! include!(concat!(env!("OUT_DIR"), "/my_icon_paths.rs"));
//! ```
//!
//! The constant names are derived from the SVG file names:
//! `arrow-right.svg` → `ARROW_RIGHT`, `star.svg` → `STAR`, etc.
//!
//! See the `eq_ui_build` crate documentation for full details.
//!
//! ## Runtime alternative
//!
//! For consumers who prefer not to set up a build script,
//! [`extract_svg_path`] extracts path data at runtime:
//!
//! ```ignore
//! use eq_ui::atoms::eq_icon_paths::extract_svg_path;
//!
//! let star = extract_svg_path(include_str!("../assets/icons/star.svg"));
//! rsx! { EqIcon { path: star } }
//! ```

// ── Bundled constants (generated by build.rs) ───────────────────────

include!(concat!(env!("OUT_DIR"), "/icon_paths.rs"));

// ── Consumer helper ─────────────────────────────────────────────────

/// Extract the `d` attribute from the first `<path>` element in an SVG string.
///
/// Runtime alternative for consumers who don't want a build script.
/// Use with `include_str!` to embed the SVG at compile time:
///
/// ```ignore
/// let icon = extract_svg_path(include_str!("assets/my-icon.svg"));
/// rsx! { EqIcon { path: icon } }
/// ```
///
/// Returns an empty string if no path data is found.
pub fn extract_svg_path(svg: &str) -> String {
    let Some(path_start) = svg.find("<path") else {
        return String::new();
    };
    let after_path = &svg[path_start..];

    let Some(d_start) = after_path.find("d=\"") else {
        return String::new();
    };
    let d_value = &after_path[d_start + 3..];

    let Some(d_end) = d_value.find('"') else {
        return String::new();
    };
    d_value[..d_end].to_string()
}
